before:
  hooks:
    - go test -v ./...
builds:
  - binary: nitro
    id: nitro
    main: ./cmd/nitro/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X github.com/craftcms/nitro/command/version.Version={{.Version}}
archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    id: nitro
    builds:
      - nitro
    replacements:
      386: i386
      amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: auto
  github:
    owner: craftcms
    name: nitro
brews:
  - tap:
      owner: craftcms
      name: homebrew-nitro
    folder: Formula
    homepage: https://getnitro.sh/
    description: Nitro is a speedy Docker-based local development environment tuned for Craft CMS
    license: MIT
    test: |
      system "#{bin}/nitro --version"
    install: |-
      bin.install "nitro"
nfpms:
  - vendor: Craft CMS
    homepage: https://getnitro.sh
    description: Nitro is a speedy Docker-based local development environment tuned for Craft CMS
    license: MIT
    formats:
      - apk
      - deb
      - rpm
