# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - binary: nitro
    id: nitro
    main: ./cmd/cli/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X github.com/craftcms/nitro/internal/cmd.Version={{.Version}}
  - binary: nitrod
    id: nitrod
    main: ./cmd/nitrod/main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X github.com/craftcms/nitro/internal/api.Version={{.Version}}
archives:
  -
    name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    id: nitro
    builds:
      - nitro
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
  -
    name_template: "nitrod_{{.Os}}_{{.Arch}}"
    id: nitrod
    builds:
      - nitrod
    replacements:
      amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: craftcms
    name: nitro
