#!/usr/bin/env php
<?php declare(strict_types=1);

error_reporting(-1);

// make sure we are on 64-bit
if (PHP_INT_SIZE !== 8) {
    throw new RuntimeException('Only 64-bit is supported at the moment');
}

define('CRAFT_VENDOR_PATH', dirname(__DIR__) . '/vendor/');

// make sure we have a CRAFT_VENDOR_PATH
if (!defined('CRAFT_VENDOR_PATH')) {
    throw new RuntimeException('The CRAFT_VENDOR_PATH must be set');
}

$packages = json_decode(file_get_contents(CRAFT_VENDOR_PATH . '/composer/installed.json'), true);
foreach ($packages as $key => $package) {
    foreach ($package as $k => $v) {
        if ($k === 'name' && $v === 'craftcms/cms') {
            $version = $packages[$key]['version'];
            continue;
        }
    }
}

// get the name of the binary
$binary = 'nitro-' . $version . '-' . strtolower(PHP_OS) . '-amd64';

// check if the binary exists
if (file_exists(CRAFT_VENDOR_PATH . 'bin' . DIRECTORY_SEPARATOR . $binary)) {
    // if it exists, pass the args to the binary
    echo 'call the binary';

    return;
}

// if it does not get the current version and download from github

// unzip the binary and place full path name into bin dir (e.g. vendor/bin/nitro-darwin-amd64)
