package caddyconv

type CaddyUpdateRequest struct {
	Srv0 Server `json:"srv0,omitempty"`
	Srv1 Server `json:"srv1,omitempty"`
}

type Server struct {
	Listen []string      `json:"listen"`
	Routes []ServerRoute `json:"routes"`
}

type ServerRoute struct {
	Handle []RouteHandle `json:"handle"`
	Match  []Match       `json:"match,omitempty"`
}

type RouteHandle struct {
	Handler   string     `json:"handler"`
	Root      string     `json:"root,omitempty"`
	Upstreams []Upstream `json:"upstreams,omitempty"`
	Hide      []string   `json:"hide,omitempty"`
}

type Match struct {
	Host []string `json:"host"`
}

type Upstream struct {
	Dial string `json:"dial,omitempty"`
}

type AutoGenerated struct {
	Srv0 struct { //server
		Listen []string   `json:"listen"`
		Routes []struct { // server route
			Handle []struct { // rotue handle
				Handler string   `json:"handler"`
				Root    string   `json:"root,omitempty"`
				Hide    []string `json:"hide,omitempty"`
			} `json:"handle"`
		} `json:"routes"`
	} `json:"srv0"`
	Srv1 struct { // server
		Listen []string   `json:"listen"`
		Routes []struct { // server route
			Handle []struct { // route handle
				Handler string `json:"handler"`
				Routes  []struct {
					Handle []struct {
						Handler   string `json:"handler"`
						Upstreams []struct {
							Dial string `json:"dial"`
						} `json:"upstreams"`
					} `json:"handle"`
				} `json:"routes"`
			} `json:"handle"`
			Match []struct {
				Host []string `json:"host"`
			} `json:"match,omitempty"`
			Terminal bool `json:"terminal"`
		} `json:"routes"`
	} `json:"srv1"`
}
